"
" Bundles
"

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'a.vim'
Bundle 'airblade/vim-gitgutter'
Bundle 'argtextobj.vim'
Bundle 'ciaranm/securemodelines'
Bundle 'coderifous/textobj-word-column.vim'
Bundle 'gmarik/vundle'
Bundle 'godlygeek/tabular'
Bundle 'goldfeld/vim-seek'
Bundle 'kana/vim-filetype-haskell'
Bundle 'kien/ctrlp.vim'
Bundle 'kien/rainbow_parentheses.vim'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'SirVer/ultisnips'
Bundle 'spolu/dwm.vim'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'w0ng/vim-hybrid'

"
" Options
"

syntax on                            " turn on syntax highlighting
filetype plugin indent on            " turn on ftplugin and indent
let mapleader = ","                  " map leader to ,
let g:hybrid_use_Xresources = 1      " use .Xresources colors for hybrid
colorscheme hybrid                   " colorscheme

set autoindent                       " copy current indent level when starting new line
set backspace=start,indent,eol       " make backspace work like 'normal' text editors
set completeopt=menu,longest         " options for insert mode completion
set cursorline                       " highlight the line the cursor is on
set expandtab                        " use spaces instead of tab characters
set gdefault                         " replace globally by default
set hidden                           " hide buffers instead of closing them
set hlsearch                         " highlight search terms
set incsearch                        " show search matches as they are found
set lazyredraw                       " don't redraw when executing macros
set linebreak                        " don't wrap on middle of words
set noswapfile                       " don't make swap file
set number                           " show line numbers
set pastetoggle=<F2>                 " toggle paste mode via F2
set ruler                            " show the line and column number
set scrolloff=8                      " start scrolling when within 8 lines near top/bottom
set shiftround                       " round indent to multiple of shiftwidth
set shiftwidth=4                     " number of spaces to use for autoindent
set showcmd                          " show the command being typed
set showmatch                        " show matching braces when text indicator is over them
set smartcase                        " case sensitive only when capital letter in expression
set softtabstop=4                    " defines number of spaces for when adding/remving tabs
set splitbelow                       " horizontal splits go to below
set splitright                       " vertical splits go to right
set tabstop=4                        " width of a tab character in spaces
set timeoutlen=300                   " don't wait so long for the next keypress
set ttyfast                          " improve smoothness of redrawing
set updatecount=0                    " we don't use no swap files
set virtualedit=block                " allow moving outside text bounds in visual block mode
set wildmenu                         " enhance command line completion
set wildmode=longest,list:full       " command prompt tab-completion
set wrap                             " wrap lines

" Backup
set backup
set backupdir=~/.vim/backups
set undofile
set undodir=~/.vim/undo

" Display invisible characters
set listchars=tab:→\ ,trail:·
set list

" Ignore unndeeded files
set wildignore+=*.bak,*.swp,*.git,*.pyc,*.pyo,*.o

"
" Mappings
"

command! W w
command! Q q
nnoremap H ^
nnoremap L $
nnoremap Y y$
nnoremap Q @@
nnoremap U :redo<CR>

" Jump to matching braces easily
nnoremap <Tab> %
vnoremap <Tab> %

" Easier moving with wrapping
nnoremap j gj
nnoremap k gk

" Disable search highlighting
nnoremap <silent><leader><Space> :nohls<CR>

" Switch between last two buffers
nnoremap <C-t> :b#<CR>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Strip all trailing whitespace from file
nnoremap <leader>tr :%s/\s\+$//<CR>:let @/=''<CR>

" Reselect pasted text
nnoremap <leader>p V`]`

"
" Plugin settings
"

" Ctrlp
nnoremap § :CtrlPBuffer<CR>
let g:ctrlp_working_path_mode = 0
let g:ctrlp_user_command = "find %s -type f | grep -v /.git/"

" EasyMotion
let g:EasyMotion_leader_key = '<Leader>'

" Fugitive
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gg :Ggrep<Space>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gb :Gblame<CR>

" NERDTree
let g:NERDTreeChDirMode = 2
let g:NERDTreeMinimalUI = 1
let g:NERDTreeIgnore    = ['\~$', '\.swp$', '\.o$', '\.pyc$', '\.hi$']
nnoremap <F12> :NERDTreeToggle<CR>

" Tabular
nnoremap <leader>= :Tabular /=<CR>
nnoremap <leader>: :Tabular /:<CR>
nnoremap <leader>\ :Tabular /\<CR>

" Secure modelines
let g:secure_modelines_modelines = 2

"
" Autocommands
"

" Less indentation for some filetypes
autocmd FileType vim,sh,zsh,PKGBUILD set ts=2 sts=2 sw=2

" Rainbow Parentheses
autocmd VimEnter * RainbowParenthesesToggleAll

"
" Functions
"

" Quickly toggle relativenumber
if exists("&relativenumber")
  function! s:ToggleRelativeNumber()
    if &relativenumber
      set norelativenumber
      let &number = b:togglernu_number
    else
      let b:togglernu_number = &number
      set relativenumber
    endif
  endfunction
  nnoremap <silent> <leader>m :<C-U>call <SID>ToggleRelativeNumber()<CR>
endif
