#!/bin/sh

# keyboard
xset r rate 350 45
setxkbmap fi nodeadkeys
xmodmap "$HOME/.speedswapper"

# X resources
xrdb -merge "$HOME/.Xresources"

# URxvt daemon
urxvtd -q -o -f &

# cursor
xsetroot -cursor_name left_ptr &
unclutter -idle 10 -jitter 5 &

# programs
(firefox-beta-bin > /dev/null 2>&1) &
xbindkeys

# check if external monitor is connected
if (xrandr | grep 'HDMI1 disconnected'); then
    xrandr --output eDP1 --mode 1440x900 --pos 0x0 --output HDMI1 --off
else
    xrandr --output eDP1 --mode 1440x900 --pos 0x0 --output HDMI1 --mode 1920x1200 --pos 1440x0
fi

# wallpaper
bgs -s "$HOME/.wallpaper"

# color profile for MacBook Air
xcalib -s eDP1 "$HOME/.config/colorprofiles/macbook.icc"

# window manager
sxhkd -f 100 &
exec bspwm
