#!/bin/sh

monster_init() {
    local ff="/tmp/monsterwm.fifo"

    monsterpager "$ff" | \
        dzen2 -h 18 -x 1920 -w 420 -ta l -e -p &
    monsterstatus | \
        dzen2 -h 18 -x 2340 -w 1500 -ta r -e -p &

    while [[ ! -p "$ff" ]]; do sleep 1; done
    exec monsterwm > "$ff"
    [[ -p "$ff" ]] && rm "$ff"
}

# keyboard
xset r rate 350 45
setxkbmap fi nodeadkeys
xmodmap "${HOME}/.speedswapper"

# X resources
xrdb -merge "${HOME}/.Xresources"

# wallpaper
bgs -s "${HOME}/.wallpaper" &

# URxvt daemon
urxvtd -q -o -f &

# cursor
xsetroot -cursor_name left_ptr &
unclutter -idle 2 -noevents &

# programs
(firefox &> /dev/null) &
(sleep 10 && urxvtc -sl 0 -name cmus -e cmus) &
(sleep 15 && urxvtc -sl 0 -name htop -e htop) &
(sleep 20 && urxvtc -sl 0 -name vifm -e vifm) &

# window manager
monster_init
