#
# Executes commands at login pre-zshrc.
#

#
# Path
#

typeset -gU path

path=(
  ~/bin
  ~/bin/toolsched/bin
  /usr/lib/colorgcc/bin
  $path
)

# Start X at login

vt=$(fgconsole 2>/dev/null)
(( vt == 1 )) && exec startx -- vt$vt
unset vt

