#
# Executes commands at login pre-zshrc.
#

#
# Path
#

typeset -gU path

path=(
  ~/bin
  ~/bin/toolsched/bin
  /usr/lib/colorgcc/bin
  $path
)

# Start X at login

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

