#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the path to Oh My Zsh.
export OMZ="$HOME/.oh-my-zsh"

# Path
typeset -gU path

path=(
  ~/bin
  ~/bin/toolsched
  /usr/lib/colorgcc/bin
  $path
)

# Language
export LANG=en_US.UTF-8

# Editors
export EDITOR='vim'
export VISUAL='vim'

# Pager
if (( $+commands[vimpager] )); then
  export PAGER='vimpager' && alias less=$PAGER
else
  export PAGER='less'

  # Set the default Less options.
  # Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
  # Remove -X and -F (exit if the content fits on one screen) to enable it.
  export LESS='-F -g -i -M -R -S -w -X -z-4'

  # Set the Less input preprocessor.
  if (( $+commands[lesspipe.sh] )); then
    export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
  fi
fi

# Browser (default)
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
else
  export BROWSER='firefox-beta-bin'
fi

