#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the path to prezto.
export OMZ="$HOME/.prezto"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
else
  export BROWSER='firefox-beta-bin'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'

#
# Pager
#

if (( $+commands[vimpager] )); then
  export PAGER='vimpager'
  alias less=$PAGER
  alias zless=$PAGER
else
  export PAGER='less'

  # Set the default Less options.
  # Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
  # Remove -X and -F (exit if the content fits on one screen) to enable it.
  export LESS='-F -g -i -M -R -S -w -X -z-4'

  # Set the Less input preprocessor.
  if (( $+commands[lesspipe.sh] )); then
    export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
  fi
fi

# Faster escape to vi mode
export KEYTIMEOUT="1"

